language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
script:
    #    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.test("VerilogFIR", coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("VerilogFIR")); using Coverage; Codecov.submit(process_folder())'
